=== archenovalis/one_sector_swi/xsd/gamestartsdiff.xsd
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE schema [
  <!ENTITY ncname "\i\c*">
  <!ENTITY qname  "(&ncname;:)?&ncname;">
  <!ENTITY aname  "@&qname;">
  <!ENTITY pos    "\[\d+\]">
  <!ENTITY attr   "\[&aname;='(.)*'\]|\[&aname;=&quot;(.)*&quot;\]">
  <!ENTITY valueq "\[(&qname;|\.)=&quot;(.)*&quot;\]">
  <!ENTITY value  "\[(&qname;|\.)='(.)*'\]|&valueq;">
  <!ENTITY cond   "&attr;|&value;|&pos;">
  <!ENTITY step   "(&qname;|\*)(&cond;)*">
  <!ENTITY arg    "&qname;">
  <!ENTITY fn     "(not\(&arg;\)|boolean\(&arg;\)|true\(\)|false\(\)|name\(\)|root\((&arg;)?\)|position\(\)|last\(\))">
  <!ENTITY func   "\[&fn;\]">
  <!ENTITY piq    "processing-instruction\((&quot;&ncname;&quot;)\)">
  <!ENTITY pi     "processing-instruction\(('&ncname;')?\)|&piq;">
  <!ENTITY id     "id\(('&ncname;')?\)|id\((&quot;&ncname;&quot;)?\)">
  <!ENTITY com    "comment\(\)">
  <!ENTITY text   "text\(\)">
  <!ENTITY nspa   "namespace::&ncname;">
  <!ENTITY cnodes "(&text;(&pos;)?)|(&com;(&pos;)?)|((&pi;)(&pos;)?)">
  <!ENTITY child  "(&cnodes;|(&step;(&func;)?))">
  <!ENTITY last   "(&child;|&aname;|&nspa;)">
  <!ENTITY path   "(/|//)?((&id;)(((/|//)&step;)*((/|//)&last;))?|(&step;(/|//))*(&last;))">
  <!ENTITY patha  "(/|//)?((&id;)(((/|//)&step;)*((/|//)&child;))?|(&step;(/|//))*(&child;))">
  <!ENTITY pathc  "(&patha;|not\(&patha;\)|&fn;)">
]>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:include schemaLocation="gamestarts.xsd" />
  
  <xs:simpleType name="xpath">
    <xs:restriction base="xs:string">
      <xs:pattern value="&path;"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="xpath-add">
    <xs:restriction base="xs:string">
      <xs:pattern value="&patha;"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="xpath-cond">
    <xs:restriction base="xs:string">
      <xs:pattern value="&pathc;"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="pos">
    <xs:restriction base="xs:string">
      <xs:enumeration value="before"/>
      <xs:enumeration value="after"/>
      <xs:enumeration value="prepend"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="type">
    <xs:restriction base="xs:string">
      <xs:pattern value="&aname;|&nspa;"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="add">
    <xs:complexContent mixed="true">
      <xs:restriction base="xs:anyType">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="selectrandom" />
            <xs:group ref="equipmentmods" />
            <xs:group ref="createship" />
            <xs:group ref="createnpc" />
            <xs:group ref="createmodule" />
            <xs:group ref="createstation" />
            <xs:group ref="createobject" />
            <xs:group ref="people" />
            <xs:group ref="loadoutelements" />
            <xs:group ref="constructionsequenceelements" />
            <xs:group ref="voicedata" />
            <xs:group ref="commonconditions_event" />
            <xs:group ref="commonconditions_nonevent" />
            <xs:group ref="commonactions" />
            <xs:element name="group" type="gamestartgroup" />
            <xs:element name="source" type="gamestartextensionsource" />
            <xs:element name="item" type="gamestartinfoitem" />
            <xs:element name="achievement" type="gamestartunlockachievement" />
            <xs:element name="userdata" type="gamestartunlockuserdata" />
            <xs:element name="text" type="gamestartloadingscreentext" />
            <xs:element name="info" type="gamestartloadingscreentext" />
            <xs:element name="position" type="position" />
            <xs:element name="rotation" type="rotation" />
            <xs:element name="player" type="gamestartplayerlocation" />
            <xs:element name="interior" type="gamestartinterior" />
            <xs:element name="ware" type="gamestartware" />
            <xs:element name="loadout" type="gamestartloadout" />
            <xs:element name="modification" type="gamestartshipmod" />
            <xs:element name="cargo" type="gamestartwares" />
            <xs:element name="pilot" type="gamestartperson" />
            <xs:element name="entry" type="gamestartencyclopediaentry" />
            <xs:element name="faction" type="gamestartknownfaction" />
            <xs:element name="space" type="gamestartknownspace" />
            <xs:element name="object" type="gamestartknownobject" />
            <xs:element name="location" type="gamestartpropertylocation" />
            <xs:element name="construction" type="gamestartconstructionsequence" />
            <xs:element name="manager" type="gamestartperson" />
            <xs:element name="station" type="gamestartpropertystation" />
            <xs:element name="ship" type="gamestartpropertyship" />
            <xs:element name="inventory" type="gamestartwares" />
            <xs:element name="blueprints" type="gamestartblueprints" />
            <xs:element name="build" type="gamestartbuild" />
            <xs:element name="research" type="gamestartresearch" />
            <xs:element name="encyclopedia" type="gamestartencyclopedia" />
            <xs:element name="timeline" type="gamestarttimeline" />
            <xs:element name="knownfactions" type="gamestartknownfactions" />
            <xs:element name="knownspace" type="gamestartknownspaces" />
            <xs:element name="knownobjects" type="gamestartknownobjects" />
            <xs:element name="property" type="gamestartproperty" />
            <xs:element name="theme" type="gamestarttheme" />
            <xs:element name="density" type="gamestartuniverseregionwares" />
            <xs:element name="time" type="gamestartuniverseregionwares" />
            <xs:element name="quotas" type="gamestartuniversequotas" />
            <xs:element name="highways" type="gamestartuniversehighways" />
            <xs:element name="regions" type="gamestartuniverseregions" />
            <xs:element name="hiddenobjects" type="gamestartuniversehiddenobjects" />
            <xs:element name="jobs" type="gamestartuniversejobs" />
            <xs:element name="god" type="gamestartuniversegod" />
            <xs:element name="masstraffic" type="gamestartuniversemasstraffic" />
            <xs:element name="factions" type="gamestartuniversefactions" />
            <xs:element name="accesslicences" type="gamestartuniverseaccesslicences" />
            <xs:element name="stories" type="gamestartuniversestorystates" />
            <xs:element name="unlock" type="gamestartunlock" />
            <xs:element name="option" type="gamestartoption" />
            <xs:element name="dependencies" type="gamestartdependencies" />
            <xs:element name="objects" type="gamestartknownbudgetobjectsparams" />
            <xs:element name="money" type="gamestartbudgettype" />
            <xs:element name="parameters" type="gamestartknownbudgetparams" />
            <xs:element name="extension" type="gamestartextension" />
            <xs:element name="cutscene" type="gamestartcutscene" />
            <xs:element name="intro" type="gamestartintro" />
            <xs:element name="type" type="gamestarttype" />
            <xs:element name="loadingscreen" type="gamestartloadingscreen" />
            <xs:element name="universe" type="gamestartuniverse" />
            <xs:element name="options" type="gamestartoptions" />
            <xs:element name="budget" type="gamestartbudget" />
            <xs:element name="custom" type="gamestartcustom" />
            <xs:element name="scenario" type="gamestartscenario" />
            <xs:element name="groups" type="gamestartgroups" />
            <xs:element name="gamestart" type="gamestart" />
            <xs:element name="gamestarts" type="gamestarts" />
            <xs:element name="dependency" />
            <xs:element name="page" />
            <xs:element name="skills" />
            <xs:element name="skill" />
            <xs:element name="equipment" />
            <xs:element name="weapon" />
            <xs:element name="shield" />
            <xs:element name="engine" />
            <xs:element name="mods" />
            <xs:element name="component" />
            <xs:element name="yield" />
            <xs:element name="replenish" />
            <xs:element name="quota" />
            <xs:element name="police" />
            <xs:element name="relations" />
            <xs:element name="relation" />
            <xs:element name="accesslicence" />
            <xs:element name="story" />
            <xs:element name="zone" />
            <xs:element name="sector" />
            <xs:element name="cluster" />
            <xs:element name="class" />
            <xs:element name="states" />
            <xs:element name="state" />
            <xs:element name="levels" />
            <xs:element name="level" />
            <xs:element name="known" />
            <xs:element name="scores" />
            <xs:element name="score" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="sel" type="xpath-add" use="required"/>
        <xs:attribute name="pos" type="pos"/>
        <xs:attribute name="type" type="type"/>
        <xs:attribute name="if" type="xpath-cond"/>
        <xs:attribute name="silent" type="xs:boolean"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="replace">
    <xs:complexContent mixed="true">
      <xs:restriction base="xs:anyType">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="selectrandom" />
            <xs:group ref="equipmentmods" />
            <xs:group ref="createship" />
            <xs:group ref="createnpc" />
            <xs:group ref="createmodule" />
            <xs:group ref="createstation" />
            <xs:group ref="createobject" />
            <xs:group ref="people" />
            <xs:group ref="loadoutelements" />
            <xs:group ref="constructionsequenceelements" />
            <xs:group ref="voicedata" />
            <xs:group ref="commonconditions_event" />
            <xs:group ref="commonconditions_nonevent" />
            <xs:group ref="commonactions" />
            <xs:element name="group" type="gamestartgroup" />
            <xs:element name="source" type="gamestartextensionsource" />
            <xs:element name="item" type="gamestartinfoitem" />
            <xs:element name="achievement" type="gamestartunlockachievement" />
            <xs:element name="userdata" type="gamestartunlockuserdata" />
            <xs:element name="text" type="gamestartloadingscreentext" />
            <xs:element name="info" type="gamestartloadingscreentext" />
            <xs:element name="position" type="position" />
            <xs:element name="rotation" type="rotation" />
            <xs:element name="player" type="gamestartplayerlocation" />
            <xs:element name="interior" type="gamestartinterior" />
            <xs:element name="ware" type="gamestartware" />
            <xs:element name="loadout" type="gamestartloadout" />
            <xs:element name="modification" type="gamestartshipmod" />
            <xs:element name="cargo" type="gamestartwares" />
            <xs:element name="pilot" type="gamestartperson" />
            <xs:element name="entry" type="gamestartencyclopediaentry" />
            <xs:element name="faction" type="gamestartknownfaction" />
            <xs:element name="space" type="gamestartknownspace" />
            <xs:element name="object" type="gamestartknownobject" />
            <xs:element name="location" type="gamestartpropertylocation" />
            <xs:element name="construction" type="gamestartconstructionsequence" />
            <xs:element name="manager" type="gamestartperson" />
            <xs:element name="station" type="gamestartpropertystation" />
            <xs:element name="ship" type="gamestartpropertyship" />
            <xs:element name="inventory" type="gamestartwares" />
            <xs:element name="blueprints" type="gamestartblueprints" />
            <xs:element name="build" type="gamestartbuild" />
            <xs:element name="research" type="gamestartresearch" />
            <xs:element name="encyclopedia" type="gamestartencyclopedia" />
            <xs:element name="timeline" type="gamestarttimeline" />
            <xs:element name="knownfactions" type="gamestartknownfactions" />
            <xs:element name="knownspace" type="gamestartknownspaces" />
            <xs:element name="knownobjects" type="gamestartknownobjects" />
            <xs:element name="property" type="gamestartproperty" />
            <xs:element name="theme" type="gamestarttheme" />
            <xs:element name="density" type="gamestartuniverseregionwares" />
            <xs:element name="time" type="gamestartuniverseregionwares" />
            <xs:element name="quotas" type="gamestartuniversequotas" />
            <xs:element name="highways" type="gamestartuniversehighways" />
            <xs:element name="regions" type="gamestartuniverseregions" />
            <xs:element name="hiddenobjects" type="gamestartuniversehiddenobjects" />
            <xs:element name="jobs" type="gamestartuniversejobs" />
            <xs:element name="god" type="gamestartuniversegod" />
            <xs:element name="masstraffic" type="gamestartuniversemasstraffic" />
            <xs:element name="factions" type="gamestartuniversefactions" />
            <xs:element name="accesslicences" type="gamestartuniverseaccesslicences" />
            <xs:element name="stories" type="gamestartuniversestorystates" />
            <xs:element name="unlock" type="gamestartunlock" />
            <xs:element name="option" type="gamestartoption" />
            <xs:element name="dependencies" type="gamestartdependencies" />
            <xs:element name="objects" type="gamestartknownbudgetobjectsparams" />
            <xs:element name="money" type="gamestartbudgettype" />
            <xs:element name="parameters" type="gamestartknownbudgetparams" />
            <xs:element name="extension" type="gamestartextension" />
            <xs:element name="cutscene" type="gamestartcutscene" />
            <xs:element name="intro" type="gamestartintro" />
            <xs:element name="type" type="gamestarttype" />
            <xs:element name="loadingscreen" type="gamestartloadingscreen" />
            <xs:element name="universe" type="gamestartuniverse" />
            <xs:element name="options" type="gamestartoptions" />
            <xs:element name="budget" type="gamestartbudget" />
            <xs:element name="custom" type="gamestartcustom" />
            <xs:element name="scenario" type="gamestartscenario" />
            <xs:element name="groups" type="gamestartgroups" />
            <xs:element name="gamestart" type="gamestart" />
            <xs:element name="gamestarts" type="gamestarts" />
            <xs:element name="dependency" />
            <xs:element name="page" />
            <xs:element name="skills" />
            <xs:element name="skill" />
            <xs:element name="equipment" />
            <xs:element name="weapon" />
            <xs:element name="shield" />
            <xs:element name="engine" />
            <xs:element name="mods" />
            <xs:element name="component" />
            <xs:element name="yield" />
            <xs:element name="replenish" />
            <xs:element name="quota" />
            <xs:element name="police" />
            <xs:element name="relations" />
            <xs:element name="relation" />
            <xs:element name="accesslicence" />
            <xs:element name="story" />
            <xs:element name="zone" />
            <xs:element name="sector" />
            <xs:element name="cluster" />
            <xs:element name="class" />
            <xs:element name="states" />
            <xs:element name="state" />
            <xs:element name="levels" />
            <xs:element name="level" />
            <xs:element name="known" />
            <xs:element name="scores" />
            <xs:element name="score" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="sel" type="xpath" use="required"/>
        <xs:attribute name="if" type="xpath-cond"/>
        <xs:attribute name="silent" type="xs:boolean"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="remove">
    <xs:attribute name="sel" type="xpath" use="required"/>
    <xs:attribute name="if" type="xpath-cond"/>
    <xs:attribute name="silent" type="xs:boolean"/>
  </xs:complexType>

  <!-- ===== Root element ==== -->

  <xs:element name="diff">
    <xs:annotation>
      <xs:documentation>
        XML Patch data
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:choice>
          <xs:element name="add" type="add">
            <xs:annotation>
              <xs:documentation>
                Add content
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="replace" type="replace">
            <xs:annotation>
              <xs:documentation>
                Replace content
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="remove" type="remove">
            <xs:annotation>
              <xs:documentation>
                Remove content
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== archenovalis/one_sector_swi/one_sector_swi/libraries/gamestarts.xml
<?xml version="1.0" encoding="utf-8"?>
<diff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/gamestartsdiff.xsd">
  <remove sel="//groups/group[@group='5']" />
  <add pos="before" sel="//groups/group[@group='1']">
    <group group="4" name="{20777, 2001}" />
    <group group="5" name="{20777, 2018}" />
  </add>


  <!--


  - majors -
  Galactic Empire - Bastion
  New Republic - Coruscant
  Mandalorian Death Watch - Mandalore
  Corporate Sector Authority - Cantonica
  Independent Commerce Guild - Hypori
  Hutt Cartel - Nar Shaddaa
  Imperial Ascendancy - Eriadu
  Anoat Federation - Anoat


  -->


  <add pos="before" sel="//gamestart[@id='x4ep1_sw_emp_navypilot']">
    <!-- name = title -->
    <gamestart id="gaj_empire" name="{20777,2002}" description="{20777,2003}" image="gamestart_91" group="4">
      <info>
        <item name="{1021,8}" value="{999840,600330}" /> <!-- Name -->
        <item name="{1021,1}" value="{999840,800508}" /> <!-- location -->
        <item name="{1021,2}" value="{999840,600350}" /> <!-- Ship -->
        <item name="{1021,3}" value="15000" />
      </info>
      <type name="{1021,94}" description="{1021,95}" recommendation="10" />
      <location galaxy="swi_galaxy_macro" sector="swi_clusterbastion_sector001_macro" />
      <player macro="character_player_tutorial_macro" money="15000" name="{999840,600330}">
        <ship macro="tie_fighter_van_macro">
          <loadout>
            <macros>
              <engine macro="engine_tiehd_macro" path="../con_engine_01" />
              <engine macro="engine_tiehd_macro" path="../con_engine_02" />
              <weapon macro="weapon_ls1_s_laser_macro" path="../con_weapon_01" optional="true" />
              <weapon macro="weapon_ls1_s_laser_macro" path="../con_weapon_02" optional="true" />
              <shield macro="shield_s_p12_macro" path="../con_shield_01" optional="1" />
            </macros>
            <ammunition>
              <ammunition macro="eq_arg_satellite_01_macro" exact="5" optional="true" />
              <ammunition macro="env_deco_nav_beacon_t1_macro" exact="5" optional="true" />
            </ammunition>
            <software>
              <software ware="software_flightassistmk1" />
              <software ware="software_scannerlongrangemk1" />
              <software ware="software_scannerobjectmk1" />
              <software ware="software_targetmk1" />
            </software>
            <virtualmacros>
              <thruster macro="thruster_gen_s_allround_01_mk1_macro" />
            </virtualmacros>
          </loadout>
        </ship>
        <inventory>
          <ware ware="weapon_gen_spacesuit_repairlaser_01_mk1" amount="1" />
          <ware ware="software_scannerobjectmk3" amount="1" />
          <ware ware="inv_timewarp" amount="1" />
        </inventory>
        <blueprints>
          <ware ware="clothingmod_0001" />
          <ware ware="clothingmod_0002" />
          <ware ware="dockarea_imp_m_station_01_hightech" />
          <ware ware="pier_imp_harbor_01" />
          <ware ware="storage_imp_s_container_01" />
          <ware ware="struct_imp_base_01" />
          <ware ware="struct_imp_cross_01" />
          <ware ware="struct_imp_vertical_01" />
          <ware ware="prod_imp_energycells" />
          <ware ware="paintmod_0006" />
          <ware ware="paintmod_0048" />
          <ware ware="paintmod_0049" />
          <ware ware="paintmod_0050" />
          <ware ware="paintmod_0097" />
          <ware ware="paintmod_0098" />
          <ware ware="paintmod_0099" />
          <ware ware="paintmod_0100" />
        </blueprints>
        <research>
          <ware ware="research_teleportation" />
          <ware ware="research_radioreceiver" />
          <ware ware="research_sensorbooster" />
          <ware ware="research_tradeinterface" />
          <ware ware="research_mod_engine_mk1" />
          <ware ware="research_mod_shield_mk1" />
          <ware ware="research_mod_ship_mk1" />
          <ware ware="research_mod_weapon_mk1" />
          <ware ware="research_module_welfare_1_pre" />
          <ware ware="research_module_welfare_1" />
        </research>
        <encyclopedia>
          <entry type="warebasket" ref="research_gamestart_common" />
        </encyclopedia>
        <theme paint="painttheme_player_01" />
      </player>
      <universe>
        <factions>
          <relations>
            <relation faction="galempire" otherfaction="player" relation="0.01593" />
          </relations>
        </factions>
      </universe>
    </gamestart>

    <gamestart id="gaj_republic" name="{20777,2004}" description="{20777,2005}" image="gamestart_14" group="4">
      <info>
        <item name="{1021,8}" value="{999840,600130}" />
        <item name="{1021,1}" value="{999840,800503}" />
        <item name="{1021,2}" value="{999840,600150}" />
        <item name="{1021,3}" value="15000" />
      </info>
      <type name="{1021,94}" description="{1021,95}" recommendation="10" />
      <location galaxy="swi_galaxy_macro" sector="swi_clustercoruscant_sector001_macro" />
      <player macro="character_player_tutorial_macro" money="15000" name="{999840,600130}">
        <ship macro="ewing_macro">
          <loadout>
            <macros>
              <engine macro="engine_incom_macro" path="../con_engine_01" />
              <engine macro="engine_incom_macro" path="../con_engine_02" />
              <weapon macro="weapon_kx5_s_laser_macro" path="../con_weapon_01" optional="true" />
              <weapon macro="weapon_kx5_s_laser_macro" path="../con_weapon_02" optional="true" />
              <weapon macro="weapon_kx5_s_laser_macro" path="../con_weapon_03" optional="true" />
              <shield macro="shield_s_p12_macro" path="../con_shield_01" optional="true" />
            </macros>
            <ammunition>
              <ammunition macro="eq_arg_satellite_01_macro" exact="5" optional="true" />
              <ammunition macro="env_deco_nav_beacon_t1_macro" exact="5" optional="true" />
              <ammunition macro="eq_arg_resourceprobe_01_macro" exact="5" optional="true" />
            </ammunition>
            <software>
              <software ware="software_flightassistmk1" />
              <software ware="software_scannerlongrangemk1" />
              <software ware="software_scannerobjectmk1" />
              <software ware="software_targetmk1" />
            </software>
            <virtualmacros>
              <thruster macro="thruster_gen_s_allround_01_mk1_macro" />
            </virtualmacros>
          </loadout>
        </ship>
        <inventory>
          <ware ware="weapon_gen_spacesuit_repairlaser_01_mk1" amount="1" />
          <ware ware="software_scannerobjectmk3" amount="1" />
          <ware ware="inv_timewarp" amount="1" />
        </inventory>
        <blueprints>
          <ware ware="clothingmod_0001" />
          <ware ware="clothingmod_0002" />
          <ware ware="module_arg_dock_m_01_lowtech" />
          <ware ware="module_arg_pier_l_01" />
          <ware ware="module_arg_stor_container_s_01" />
          <ware ware="module_arg_conn_base_01" />
          <ware ware="module_arg_conn_cross_01" />
          <ware ware="module_arg_conn_vertical_01" />
          <ware ware="module_gen_prod_energycells_01" />
          <ware ware="module_arg_prod_meat_01" />
          <ware ware="paintmod_0006" />
          <ware ware="paintmod_0048" />
          <ware ware="paintmod_0049" />
          <ware ware="paintmod_0050" />
          <ware ware="paintmod_0097" />
          <ware ware="paintmod_0098" />
          <ware ware="paintmod_0099" />
          <ware ware="paintmod_0100" />
        </blueprints>
        <research>
          <ware ware="research_teleportation" />
          <ware ware="research_radioreceiver" />
          <ware ware="research_sensorbooster" />
          <ware ware="research_tradeinterface" />
          <ware ware="research_mod_engine_mk1" />
          <ware ware="research_mod_shield_mk1" />
          <ware ware="research_mod_ship_mk1" />
          <ware ware="research_mod_weapon_mk1" />
          <ware ware="research_module_welfare_1_pre" />
          <ware ware="research_module_welfare_1" />

        </research>
        <encyclopedia>
          <entry type="warebasket" ref="research_gamestart_common" />
        </encyclopedia>
        <theme paint="painttheme_player_01" />
      </player>
      <universe>
        <factions>
          <relations>
            <relation faction="newrepublic" otherfaction="player" relation="0.01593" />
          </relations>
        </factions>
      </universe>
    </gamestart>

    <gamestart id="gaj_mando" name="{20777,2006}" description="{20777,2007}" image="gamestart_mando" group="4">
      <info>
        <item name="{1021,8}" value="{999840,600830}" />
        <item name="{1021,1}" value="{999840,911201}" />
        <item name="{1021,2}" value="{999840,600850}" />
        <item name="{1021,3}" value="15000" />
      </info>
      <type name="{1021,94}" description="{1021,95}" />
      <location galaxy="swi_galaxy_macro" sector="swi_clustermandalore_sector001_macro" />
      <player macro="character_player_split_gamestart2_macro" money="15000" name="{999840,600830}">
        <ship macro="m4_dune_macro">
          <loadout>
            <macros>
              <engine macro="engine_incom_macro" path="../con_engine_01" />
              <weapon macro="weapon_gatling_macro" path="../con_weapon_01" />
              <weapon macro="weapon_gatling_macro" path="../con_weapon_02" />
              <weapon macro="weapon_blaster_s_laser_macro" path="../con_weapon_03" />
              <weapon macro="weapon_blaster_s_laser_macro" path="../con_weapon_04" />
