=== archenovalis/one_sector_swi/xsd/librariesdiff.xsd
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE schema [
  <!ENTITY ncname "\i\c*">
  <!ENTITY qname  "(&ncname;:)?&ncname;">
  <!ENTITY aname  "@&qname;">
  <!ENTITY pos    "\[\d+\]">
  <!ENTITY attr   "\[&aname;='(.)*'\]|\[&aname;=&quot;(.)*&quot;\]">
  <!ENTITY valueq "\[(&qname;|\.)=&quot;(.)*&quot;\]">
  <!ENTITY value  "\[(&qname;|\.)='(.)*'\]|&valueq;">
  <!ENTITY cond   "&attr;|&value;|&pos;">
  <!ENTITY step   "(&qname;|\*)(&cond;)*">
  <!ENTITY arg    "&qname;">
  <!ENTITY fn     "(not\(&arg;\)|boolean\(&arg;\)|true\(\)|false\(\)|name\(\)|root\((&arg;)?\)|position\(\)|last\(\))">
  <!ENTITY func   "\[&fn;\]">
  <!ENTITY piq    "processing-instruction\((&quot;&ncname;&quot;)\)">
  <!ENTITY pi     "processing-instruction\(('&ncname;')?\)|&piq;">
  <!ENTITY id     "id\(('&ncname;')?\)|id\((&quot;&ncname;&quot;)?\)">
  <!ENTITY com    "comment\(\)">
  <!ENTITY text   "text\(\)">
  <!ENTITY nspa   "namespace::&ncname;">
  <!ENTITY cnodes "(&text;(&pos;)?)|(&com;(&pos;)?)|((&pi;)(&pos;)?)">
  <!ENTITY child  "(&cnodes;|(&step;(&func;)?))">
  <!ENTITY last   "(&child;|&aname;|&nspa;)">
  <!ENTITY path   "(/|//)?((&id;)(((/|//)&step;)*((/|//)&last;))?|(&step;(/|//))*(&last;))">
  <!ENTITY patha  "(/|//)?((&id;)(((/|//)&step;)*((/|//)&child;))?|(&step;(/|//))*(&child;))">
  <!ENTITY pathc  "(&patha;|not\(&patha;\)|&fn;)">
]>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:include schemaLocation="libraries.xsd" />
  
  <xs:simpleType name="xpath">
    <xs:restriction base="xs:string">
      <xs:pattern value="&path;"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="xpath-add">
    <xs:restriction base="xs:string">
      <xs:pattern value="&patha;"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="xpath-cond">
    <xs:restriction base="xs:string">
      <xs:pattern value="&pathc;"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="pos">
    <xs:restriction base="xs:string">
      <xs:enumeration value="before"/>
      <xs:enumeration value="after"/>
      <xs:enumeration value="prepend"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="type">
    <xs:restriction base="xs:string">
      <xs:pattern value="&aname;|&nspa;"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="add">
    <xs:complexContent mixed="true">
      <xs:restriction base="xs:anyType">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="selectrandom" />
            <xs:group ref="equipmentmods" />
            <xs:group ref="createship" />
            <xs:group ref="createnpc" />
            <xs:group ref="createmodule" />
            <xs:group ref="createstation" />
            <xs:group ref="createobject" />
            <xs:group ref="people" />
            <xs:group ref="loadoutelements" />
            <xs:group ref="constructionsequenceelements" />
            <xs:group ref="voicedata" />
            <xs:group ref="commonconditions_event" />
            <xs:group ref="commonconditions_nonevent" />
            <xs:group ref="commonactions" />
            <xs:element name="category" type="shipdbcategory" />
            <xs:element name="order" type="joborder" />
            <xs:element name="task" type="task" />
            <xs:element name="quota" type="basejobquota" />
            <xs:element name="quotas" type="gamestartjobquotas" />
            <xs:element name="position" type="positionrange" />
            <xs:element name="location" type="godlocationfilters" />
            <xs:element name="shaderparams" type="worldshaderparams" />
            <xs:element name="ships" />
            <xs:element name="ship" />
            <xs:element name="characters" />
            <xs:element name="character" />
            <xs:element name="modules" />
            <xs:element name="module" />
            <xs:element name="rooms" />
            <xs:element name="room" />
            <xs:element name="props" />
            <xs:element name="prop" />
            <xs:element name="limits" />
            <xs:element name="limit" />
            <xs:element name="modulesets" />
            <xs:element name="set" />
            <xs:element name="race" />
            <xs:element name="stations" />
            <xs:element name="station" />
            <xs:element name="param" />
            <xs:element name="distance" />
            <xs:element name="job" />
            <xs:element name="basket" />
            <xs:element name="orders" />
            <xs:element name="tasks" />
            <xs:element name="economy" />
            <xs:element name="security" />
            <xs:element name="sunlight" />
            <xs:element name="factions" />
            <xs:element name="faction" />
            <xs:element name="policefactions" />
            <xs:element name="policefaction" />
            <xs:element name="stationfactions" />
            <xs:element name="stationfaction" />
            <xs:element name="factionraces" />
            <xs:element name="factionrace" />
            <xs:element name="stationfactionraces" />
            <xs:element name="stationfactionrace" />
            <xs:element name="factionlicences" />
            <xs:element name="factionlicence" />
            <xs:element name="commander" />
            <xs:element name="encounters" />
            <xs:element name="environment" />
            <xs:element name="modifiers" />
            <xs:element name="time" />
            <xs:element name="expirationtime" />
            <xs:element name="subordinates" />
            <xs:element name="subordinate" />
            <xs:element name="masstraffic" />
            <xs:element name="jobs" />
            <xs:element name="gamestart" />
            <xs:element name="corerange" />
            <xs:element name="region" />
            <xs:element name="objects" />
            <xs:element name="object" />
            <xs:element name="defaults" />
            <xs:element name="products" />
            <xs:element name="product" />
            <xs:element name="god" />
            <xs:element name="shaderparam" />
            <xs:element name="dataset" />
            <xs:element name="properties" />
            <xs:element name="boundaries" />
            <xs:element name="identification" />
            <xs:element name="resources" />
            <xs:element name="ware" />
            <xs:element name="sounds" />
            <xs:element name="music" />
            <xs:element name="fightmusic" />
            <xs:element name="area" />
            <xs:element name="backgroundcolor" />
            <xs:element name="system" />
            <xs:element name="space" />
            <xs:element name="suns" />
            <xs:element name="sun" />
            <xs:element name="planets" />
            <xs:element name="planet" />
            <xs:element name="moons" />
            <xs:element name="moon" />
            <xs:element name="worlds" />
            <xs:element name="world" />
            <xs:element name="access" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="sel" type="xpath-add" use="required"/>
        <xs:attribute name="pos" type="pos"/>
        <xs:attribute name="type" type="type"/>
        <xs:attribute name="if" type="xpath-cond"/>
        <xs:attribute name="silent" type="xs:boolean"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="replace">
    <xs:complexContent mixed="true">
      <xs:restriction base="xs:anyType">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="selectrandom" />
            <xs:group ref="equipmentmods" />
            <xs:group ref="createship" />
            <xs:group ref="createnpc" />
            <xs:group ref="createmodule" />
            <xs:group ref="createstation" />
            <xs:group ref="createobject" />
            <xs:group ref="people" />
            <xs:group ref="loadoutelements" />
            <xs:group ref="constructionsequenceelements" />
            <xs:group ref="voicedata" />
            <xs:group ref="commonconditions_event" />
            <xs:group ref="commonconditions_nonevent" />
            <xs:group ref="commonactions" />
            <xs:element name="category" type="shipdbcategory" />
            <xs:element name="order" type="joborder" />
            <xs:element name="task" type="task" />
            <xs:element name="quota" type="basejobquota" />
            <xs:element name="quotas" type="gamestartjobquotas" />
            <xs:element name="position" type="positionrange" />
            <xs:element name="location" type="godlocationfilters" />
            <xs:element name="shaderparams" type="worldshaderparams" />
            <xs:element name="ships" />
            <xs:element name="ship" />
            <xs:element name="characters" />
            <xs:element name="character" />
            <xs:element name="modules" />
            <xs:element name="module" />
            <xs:element name="rooms" />
            <xs:element name="room" />
            <xs:element name="props" />
            <xs:element name="prop" />
            <xs:element name="limits" />
            <xs:element name="limit" />
            <xs:element name="modulesets" />
            <xs:element name="set" />
            <xs:element name="race" />
            <xs:element name="stations" />
            <xs:element name="station" />
            <xs:element name="param" />
            <xs:element name="distance" />
            <xs:element name="job" />
            <xs:element name="basket" />
            <xs:element name="orders" />
            <xs:element name="tasks" />
            <xs:element name="economy" />
            <xs:element name="security" />
            <xs:element name="sunlight" />
            <xs:element name="factions" />
            <xs:element name="faction" />
            <xs:element name="policefactions" />
            <xs:element name="policefaction" />
            <xs:element name="stationfactions" />
            <xs:element name="stationfaction" />
            <xs:element name="factionraces" />
            <xs:element name="factionrace" />
            <xs:element name="stationfactionraces" />
            <xs:element name="stationfactionrace" />
            <xs:element name="factionlicences" />
            <xs:element name="factionlicence" />
            <xs:element name="commander" />
            <xs:element name="encounters" />
            <xs:element name="environment" />
            <xs:element name="modifiers" />
            <xs:element name="time" />
            <xs:element name="expirationtime" />
            <xs:element name="subordinates" />
            <xs:element name="subordinate" />
            <xs:element name="masstraffic" />
            <xs:element name="jobs" />
            <xs:element name="gamestart" />
            <xs:element name="corerange" />
            <xs:element name="region" />
            <xs:element name="objects" />
            <xs:element name="object" />
            <xs:element name="defaults" />
            <xs:element name="products" />
            <xs:element name="product" />
            <xs:element name="god" />
            <xs:element name="shaderparam" />
            <xs:element name="dataset" />
            <xs:element name="properties" />
            <xs:element name="boundaries" />
            <xs:element name="identification" />
            <xs:element name="resources" />
            <xs:element name="ware" />
            <xs:element name="sounds" />
            <xs:element name="music" />
            <xs:element name="fightmusic" />
            <xs:element name="area" />
            <xs:element name="backgroundcolor" />
            <xs:element name="system" />
            <xs:element name="space" />
            <xs:element name="suns" />
            <xs:element name="sun" />
            <xs:element name="planets" />
            <xs:element name="planet" />
            <xs:element name="moons" />
            <xs:element name="moon" />
            <xs:element name="worlds" />
            <xs:element name="world" />
            <xs:element name="access" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="sel" type="xpath" use="required"/>
        <xs:attribute name="if" type="xpath-cond"/>
        <xs:attribute name="silent" type="xs:boolean"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="remove">
    <xs:attribute name="sel" type="xpath" use="required"/>
    <xs:attribute name="if" type="xpath-cond"/>
    <xs:attribute name="silent" type="xs:boolean"/>
  </xs:complexType>

  <!-- ===== Root element ==== -->

  <xs:element name="diff">
    <xs:annotation>
      <xs:documentation>
        XML Patch data
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:choice>
          <xs:element name="add" type="add">
            <xs:annotation>
              <xs:documentation>
                Add content
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="replace" type="replace">
            <xs:annotation>
              <xs:documentation>
                Replace content
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="remove" type="remove">
            <xs:annotation>
              <xs:documentation>
                Remove content
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== archenovalis/one_sector_swi/one_sector_swi/libraries/mapdefaults.xml
<?xml version='1.0' encoding='utf-8'?>
<diff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/librariesdiff.xsd">
  <remove sel="/defaults/dataset[@macro='swi_clusteradarlon_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustercelesta_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterdagobah_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterdelrakinn_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterfirrerre_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustergaulus_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterimynusoph_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterkalee_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterkuna_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustermanaan_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustermillagro_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustermytus_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterpolismassa_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterrentasia_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustersaleucami_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustersmugglersrun_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustertargonn_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustertriton_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusteruyter_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterwrea_macro']/properties/area/@factionlogic" />

  <add sel="//dataset[@macro='swi_clustercrustai_macro']/properties/area" type="@tags">nopirates</add>
  <add sel="//dataset[@macro='swi_clustermaw_macro']/properties/area" type="@tags">nopirates guardian</add>
  <add sel="//dataset[@macro='swi_clusterordoplutonia_macro']/properties/area" type="@tags">nopirates guardian</add>
  <add sel="//dataset[@macro='swi_clustersump_macro']/properties/area" type="@tags">nopirates guardian</add>
  <add sel="//dataset[@macro='swi_clusteratrisia_macro']/properties/area" type="@tags">nopirates guardian</add>
  <add sel="//dataset[@macro='swi_clusteranteevy_macro']/properties/area" type="@tags">nopirates guardian</add>
  <add sel="//dataset[@macro='swi_clusterbaros_macro']/properties/area" type="@tags">nopirates guardian</add>
  <add sel="//dataset[@macro='swi_clustermorellia_macro']/properties/area" type="@tags">nopirates guardian</add>
  <add sel="//dataset[@macro='swi_clusterur3_macro']/properties/area" type="@tags">nopirates guardian</add>

  <!-- guardian sectors
  <remove sel="/defaults/dataset[@macro='swi_clustermaw_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterordoplutonia_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustersump_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusteratrisia_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusteranteevy_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clusterbaros_macro']/properties/area/@factionlogic" />
  <remove sel="/defaults/dataset[@macro='swi_clustermorellia_macro']/properties/area/@factionlogic" />
  -->

  <add sel="//dataset[@macro='swi_clustercrustai_macro']/properties">
    <system>
      <planets>
        <planet part="Sphere002">
          <moons>
            <moon part="Sphere003" />
          </moons>
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clusterlahmu_macro']/properties">
    <system>
      <planets>
        <planet part="part_earthlike">
          <moons>
            <moon part="moon" />
            <moon part="moon002" />
          </moons>
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clustercoruscant_macro']/properties">
    <system>
      <planets>
        <planet part="planet_coruscant">
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clustermandalore_macro']/properties">
    <system>
      <planets>
        <planet part="part_oof_planet">
          <moons>
            <moon part="Sphere003" />
          </moons>
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clusterhypori_macro']/properties">
    <system>
      <planets>
        <planet part="Sphere001">
          <moons>
            <moon part="planet001b" />
          </moons>
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clustercantonica_macro']/properties">
    <system>
      <planets>
        <planet part="part_earthlike">
          <moons>
            <moon part="moon" />
          </moons>
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clusteranpath_macro']/properties">
    <system>
      <planets>
        <planet part="part_earthlike">
          <moons>
            <moon part="moon" />
            <moon part="part_earthlike001" />
          </moons>
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clustereriadu_macro']/properties">
    <system>
      <planets>
        <planet part="part_earthlike">
          <moons>
            <moon part="moon" />
          </moons>
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clusternarshadda_macro']/properties">
    <system>
      <planets>
        <planet part="planet_nar_shaddaa">
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clusterhapes_macro']/properties">
    <system>
      <planets>
        <planet part="moon">
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clusterkamino_macro']/properties">
    <system>
      <planets>
        <planet part="part_earthlike">
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clusternaboo_macro']/properties">
    <system>
      <planets>
        <planet part="planet001">
        </planet>
      </planets>
    </system>
  </add>
  <add sel="//dataset[@macro='swi_clusterkorriban_macro']/properties">
    <system>
      <planets>
        <planet part="planet_korriban">
        </planet>
      </planets>
    </system>
  </add>
</diff>
